### ISSUE TITLE
Installing from requirements fails

### ISSUE THREAD

**Issue by joaodlf** [facebookincubator/prophet#127]
I'm using pip 9.0.1 and having issues installing prophet from a requirements file.

Example requirements.txt:
```
Cython==0.24
fbprophet==0.1.post1
numpy==1.12.0
pandas==0.19.2
pystan==2.14.0.0
python-dateutil==2.6.0
pytz==2016.10
six==1.10.0
```

(These should be the bare requirements to install prophet)

Here is the output of a pip install:

```
# pip install -r requirements.txt --no-cache-dir
Collecting Cython==0.24 (from -r requirements.txt (line 1))
  Downloading Cython-0.24-cp27-cp27mu-manylinux1_x86_64.whl (5.9MB)
    100% |████████████████████████████████| 5.9MB 33.8MB/s
Collecting fbprophet==0.1.post1 (from -r requirements.txt (line 2))
  Downloading fbprophet-0.1.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7F2dAF/fbprophet/setup.py", line 96, in <module>
        """
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/env/lib/python2.7/site-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/tmp/env/lib/python2.7/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/tmp/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/tmp/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/tmp/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
        return installer(requirement)
      File "/tmp/env/lib/python2.7/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/tmp/env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/tmp/env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 700, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/tmp/env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/tmp/env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/tmp/env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1108, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with Cython>=0.22 and NumPy are required.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7F2dAF/fbprophet/
```

If fbprophet is removed from the requirements file, everything installs as expected - also important - fbprophet will install properly if a `pip install fbprophet` is executed after.

I don't know the internals of pip (and this could very well be an issue with pip) but it looks like easy_install is attempting to run before cython and numpy are installed. I have never seen this behaviour, so I decided to post the issue on this package. 

This makes it very complicated to integrate fbprophet in our deployment methodology (packages MUST be installed via a requirements file).

Tested in both macos sierra and Centos 7.

**Comment by bletham** [comment]
It looks like the error is being raised by PyStan here:
https://github.com/stan-dev/pystan/blob/e9fc7336c338417232497217f4028a0f2654b1e6/setup.py#L221

I'm really fuzzy on why this would be caused by including fbprophet in the requirements but not just by including pystan. What do you have for `setup_requires` and `install_requires` in your `setup.py` maybe?

**Comment by bletham** [comment]
If there are any further issues here please reopen, but I'm going to close for now since I don't yet see any changes to be made to Prophet.

**Comment by maximegregoire** [comment]
I have the same problem when including Prophet in my setup.py requirements 😢  I have tried adding Prophet to `install_requires` then `setup_requires` without success.

**Comment by maximegregoire** [comment]
This was fixed by [231](https://github.com/facebookincubator/prophet/pull/231) I believe. The reason I was getting this was because I used v1.0.

**Comment by bletham** [comment]
Oh, wonderful, thanks for figuring that out!

**Comment by jogo** [comment]
Any plans to release this fix? The issue is still present in the most recent version on pypi (0.1.1).

**Comment by bletham** [comment]
Coming out later this week!

**Comment by jogo** [comment]
Thanks @bletham!
