### ISSUE TITLE
TypeError: data type "datetime" not understood When fitting Non-daily data

### ISSUE THREAD

**Issue by ByeongkiJeong** [facebookincubator/prophet#225]
I refered this tutorial: https://facebookincubator.github.io/prophet/docs/non-daily_data.html
and I got this error. I don't solve this problem! Does anyone can give me a solution?

I use python 3.5.2 in anaconda on windows10 x64.

ps. It may not cause dataset, because same problem has occured in example data(https://github.com/facebookincubator/prophet/blob/master/examples/example_retail_sales.csv)

<b>This is error message</b>
Traceback (most recent call last):
  File "d:\workspace_python\pat_rnn\09.Prophet.py", line 16, in <module>
    model = Prophet().fit(train)
  File "C:\Users\user\Anaconda3\lib\site-packages\fbprophet\forecaster.py", line 486, in fit
    history = self.setup_dataframe(history, initialize_scales=True)
  File "C:\Users\user\Anaconda3\lib\site-packages\fbprophet\forecaster.py", line 179, in setup_dataframe
    df['t'] = (df['ds'] - self.start) / self.t_scale
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\ops.py", line 696, in wrapper
    converted = _Op.get_op(left, right, name, na_op)
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\ops.py", line 330, in get_op
    return _TimeOp(left, right, name, na_op)
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\ops.py", line 343, in __init__
    lvalues = self._convert_to_array(left, name=name)
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\ops.py", line 454, in _convert_to_array
    if (inferred_type in ('datetime64', 'datetime', 'date', 'time') or
TypeError: data type "datetime" not understood

<b>This is my code</b>
import pandas as pd
import numpy as np
from fbprophet import Prophet

dataset = pd.read_csv('09.csv')
dataset['y'] = np.log(dataset['y'])

train_size = int(len(dataset) * 0.7)
test_size = len(dataset) - train_size
train, test = dataset.iloc[0:train_size,:], dataset.iloc[train_size:,:]

model = Prophet().fit(train)

future = model.make_future_dataframe(periods=test_size, freq='M')
testPredict = model.predict(future)
model.plot(testPredict)

<b>And this is my data (first 10 row)</b>
ds,y
1950-01-01,1
1950-02-01,1
1950-03-01,0
1950-04-01,0
1950-05-01,1
1950-06-01,1
1950-07-01,1
1950-08-01,0
1950-09-01,0
1950-10-01,2

**Comment by ByeongkiJeong** [comment]
Close this issue, cuz this is solved.
This error message is unseened after update pandas from 0.19.2 to 0.20.2.

**Comment by dimoibiehg** [comment]
Apparently, it is not solved. Follow this issue: https://github.com/facebook/prophet/issues/256
