### ISSUE TITLE
Weekday component graph labels shifted by 1 day

### ISSUE THREAD

**Issue by ninduni** [facebookincubator/prophet#41]
We should be seeing peaks on Friday and Sunday, but instead see them on Monday and Saturday
![screen shot 2017-02-27 at 3 36 26 pm](https://cloud.githubusercontent.com/assets/3334616/23385000/3ba8237a-fd02-11e6-872d-3be3a4c0561e.png)
I'd be willing to admit that I was wrong about where our peaks lie, except for the weird lack of label on the last tick, and the fact that the documentation shows this graph starting on Sunday.

**Comment by Tafkas** [comment]
This has been fixed by #28

**Comment by bletham** [comment]
Thanks for the bug report. Like @Tafkas said this was fixed in the Github version, if you re-install from Github it should work correctly.

**Comment by dreyco676** [comment]
Has this been pulled into what's on pip yet? I'm still seeing this issue (only for the chart)

**Comment by bletham** [comment]
Yes, this was fixed. Can you check your version of Prophet?
```
import fbprophet
fbprophet.__version__
```
